name: Branch Name Check
on:
  pull_request:
    branches:
      - '*'

jobs:
  branch-name-check:
    runs-on: self-hosted
    steps:
      - name: Check branch name
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          if [[ ! "$GITHUB_HEAD_REF" =~ ^(feature|bugfix|hotfix|release)/ ]]; then
            echo "Branch name does not follow the conventions! Expected prefix: feature/, bugfix/, hotfix/, or release/
            Your branch name is '$GITHUB_HEAD_REF'"
            exit 1
          fi
