name: Branch Name Check
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          if [[ ! "$GITHUB_REF_NAME" =~ ^(feature|bugfix|hotfix|release)/ ]]; then
            echo "Branch name does not follow the conventions! Expected prefix: feature/, bugfix/, hotfix/, or release/
            Your branch name is '$GITHUB_REF_NAME'"
            exit 1
          fi
