name: Dockerize

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Short Commit SHA
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: your-dockerhub-username/demo-repository:${{ steps.vars.outputs.short_sha }}
