name: Build and Deploy Pipeline

on:
  push:
    branches:
      - main

jobs:
  proof_html:
    name: Proof HTML
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Proof HTML
        uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./

  sonar_analysis:
    name: Sonar Analysis
    runs-on: self-hosted
    needs: proof_html
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full clone for accurate analysis
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  dockerize:
    name: Build Docker Image
    runs-on: self-hosted
    needs: sonar_analysis
    outputs:
      image_tag: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Extract Short Commit SHA
        id: vars
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: mustafakrc/demo-repository:${{ steps.vars.outputs.short_sha }}
      - name: Save Docker Image as Artifact
        run: |
          docker save mustafakrc/demo-repository:${{ steps.vars.outputs.short_sha }} -o image.tar
        shell: bash
      - name: Upload Image Artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: image.tar
          retention-days: 1 # Delete the artifact after 1 day

  trivy_scan:
    name: Security Scan with Trivy
    runs-on: self-hosted
    needs: dockerize
    steps:
      - name: Download Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: image
      - name: Load Docker Image
        run: docker load -i image.tar # load the image from the artifact
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: mustafakrc/demo-repository:${{ needs.dockerize.outputs.image_tag }}
          format: table
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'

  publish:
    name: Publish Docker Image
    runs-on: self-hosted
    needs: trivy_scan
    if: ${{ needs.trivy_scan.result == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            mustafakrc/demo-repository:${{ needs.dockerize.outputs.image_tag }}
            mustafakrc/demo-repository:latest
