name: Publish Docker Image

on:
  workflow_run:
    workflows: ["Trivy Scan"]
    types:
      - completed

jobs:
  publish:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Short Commit SHA
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            your-dockerhub-username/demo-repository:${{ steps.vars.outputs.short_sha }}
            your-dockerhub-username/demo-repository:latest
