name: Trivy Scan

on:
  workflow_run:
    workflows: ["Dockerize"]
    types:
      - completed

jobs:
  scan:
    name: Security Scan with Trivy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract Short Commit SHA
        id: vars
        run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: your-dockerhub-username/demo-repository:${{ steps.vars.outputs.short_sha }}

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@0.27.0
        with:
          image-ref: your-dockerhub-username/demo-repository:${{ steps.vars.outputs.short_sha }}
